/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import type { JSX } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle003_Black_0: THREE.Mesh;
    Circle003_Metal_0: THREE.Mesh;
    Circle005_Black_0: THREE.Mesh;
    Circle005_Metal_0: THREE.Mesh;
    Circle006_Metal_0: THREE.Mesh;
    Circle007_Metal_0: THREE.Mesh;
    Cube012_Metal_0: THREE.Mesh;
    Cube013_Metal_0: THREE.Mesh;
    Cube016_Metal_0: THREE.Mesh;
    Cube017_Metal_0: THREE.Mesh;
    Cube019_Metal_0: THREE.Mesh;
    Cylinder_Black_Glossy001_0: THREE.Mesh;
    Cylinder_Black_Glossy_0: THREE.Mesh;
    Cylinder_Black_transp_0: THREE.Mesh;
    Cylinder_Main_Color_0: THREE.Mesh;
    Cylinder_Metal_0: THREE.Mesh;
    Cylinder_Transparent_0: THREE.Mesh;
    Cylinder001_Black_0: THREE.Mesh;
    Cylinder001_Metal_0: THREE.Mesh;
    Cylinder002_Black_Glossy001_0: THREE.Mesh;
    Cylinder002_Black_Glossy_0: THREE.Mesh;
    Cylinder002_Black_transp_0: THREE.Mesh;
    Cylinder002_Main_Color_0: THREE.Mesh;
    Cylinder002_Metal_0: THREE.Mesh;
    Cylinder003_Black_Glossy001_0: THREE.Mesh;
    Cylinder003_Black_Glossy_0: THREE.Mesh;
    Cylinder003_Black_transp_0: THREE.Mesh;
    Cylinder003_Main_Color_0: THREE.Mesh;
    Cylinder003_Metal_0: THREE.Mesh;
    Cylinder003_Transparent_0: THREE.Mesh;
    Cylinder004_Black_Glossy001_0: THREE.Mesh;
    Cylinder004_Black_Glossy_0: THREE.Mesh;
    Cylinder004_Black_transp_0: THREE.Mesh;
    Cylinder004_Main_Color_0: THREE.Mesh;
    Cylinder004_Metal_0: THREE.Mesh;
    Cylinder004_Transparent_0: THREE.Mesh;
    Cylinder006_Black_0: THREE.Mesh;
    Cylinder006_Metal_0: THREE.Mesh;
    Cylinder008_Black_0: THREE.Mesh;
    Cylinder008_Metal_0: THREE.Mesh;
    Cylinder009_Black_0: THREE.Mesh;
    Cylinder009_Metal_0: THREE.Mesh;
    Cylinder010_Black_0: THREE.Mesh;
    Cylinder010_Metal_0: THREE.Mesh;
    Cylinder013_Metal_0: THREE.Mesh;
    Cylinder014_Metal_0: THREE.Mesh;
    Cylinder015__0: THREE.Mesh;
    Cylinder016_Metal_0: THREE.Mesh;
    Cylinder017_Metal_0: THREE.Mesh;
    Cylinder018_Metal_0: THREE.Mesh;
    Cylinder019_Metal_0: THREE.Mesh;
    Cylinder020_Metal_0: THREE.Mesh;
    Cylinder021_Metal_0: THREE.Mesh;
    Cylinder022_Black_0: THREE.Mesh;
    Cylinder022_Metal_0: THREE.Mesh;
    Cylinder023_Metal_0: THREE.Mesh;
    Cylinder025_Black_0: THREE.Mesh;
    Cylinder025_Metal_0: THREE.Mesh;
    Cylinder027_Metal_0: THREE.Mesh;
    Cylinder028_Metal_0: THREE.Mesh;
    Cylinder029_Metal_0: THREE.Mesh;
    Cylinder030_Black_0: THREE.Mesh;
    Cylinder030_Metal_0: THREE.Mesh;
    Cylinder031_Black_0: THREE.Mesh;
    Cylinder031_Metal_0: THREE.Mesh;
    Cylinder033_Metal_0: THREE.Mesh;
    Cylinder034_Black_0: THREE.Mesh;
    Cylinder034_Metal_0: THREE.Mesh;
    Cylinder035_Black_0: THREE.Mesh;
    Cylinder035_Metal_0: THREE.Mesh;
    Cylinder036_Black_0: THREE.Mesh;
    Cylinder036_Metal_0: THREE.Mesh;
    Cylinder037_Black_0: THREE.Mesh;
    Cylinder037_Metal_0: THREE.Mesh;
    Cylinder038_Black_0: THREE.Mesh;
    Cylinder038_Metal_0: THREE.Mesh;
    Cylinder039_Black_0: THREE.Mesh;
    Cylinder039_Metal_0: THREE.Mesh;
    Cylinder040_Black_0: THREE.Mesh;
    Cylinder040_Metal_0: THREE.Mesh;
    Cylinder041_Black_0: THREE.Mesh;
    Cylinder041_Metal_0: THREE.Mesh;
    Cylinder042_Metal_0: THREE.Mesh;
    Cylinder043_Metal_0: THREE.Mesh;
    Cylinder044_Metal_0: THREE.Mesh;
    Cylinder045_Metal_0: THREE.Mesh;
    Cylinder046_Metal_0: THREE.Mesh;
    Cylinder047_Metal_0: THREE.Mesh;
    Cylinder048_Metal_0: THREE.Mesh;
    Cylinder049_Beige_0: THREE.Mesh;
    Cylinder049_Black_0: THREE.Mesh;
    Cylinder049_Metal_0: THREE.Mesh;
    Cylinder050__0: THREE.Mesh;
    Cylinder051_Metal_0: THREE.Mesh;
    Cylinder052_Metal_0: THREE.Mesh;
    Cylinder053_Metal_0: THREE.Mesh;
    Cylinder054_Metal_0: THREE.Mesh;
    Cylinder055_Metal_0: THREE.Mesh;
    Cylinder056_Metal_0: THREE.Mesh;
    Cylinder057__0: THREE.Mesh;
    Cylinder058_Metal_0: THREE.Mesh;
    Cylinder059_Metal_0: THREE.Mesh;
    Cylinder063_Black_0: THREE.Mesh;
    Cylinder064_Black_0: THREE.Mesh;
    Cylinder065_Metal_0: THREE.Mesh;
    Cylinder066_Metal_0: THREE.Mesh;
    Cylinder067_Black_Glossy001_0: THREE.Mesh;
    Cylinder067_Black_Glossy_0: THREE.Mesh;
    Cylinder067_Black_transp_0: THREE.Mesh;
    Cylinder067_Main_Color_0: THREE.Mesh;
    Cylinder067_Metal_0: THREE.Mesh;
    Cylinder067_Transparent_0: THREE.Mesh;
    Cylinder068_Black_0: THREE.Mesh;
    Cylinder069_Metal_0: THREE.Mesh;
    Plane001__0: THREE.Mesh;
  };
  materials: {
    Black: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    ["Black_Glossy.001"]: THREE.MeshStandardMaterial;
    Black_Glossy: THREE.MeshStandardMaterial;
    Black_transp: THREE.MeshStandardMaterial;
    Main_Color: THREE.MeshStandardMaterial;
    Transparent: THREE.MeshStandardMaterial;
    ["Cylinder.015__0"]: THREE.MeshStandardMaterial;
    Beige: THREE.MeshStandardMaterial;
  };
};

export function DrumKit2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models/drumKit2.glb"
  ) as unknown as GLTFResult;

  // DEBUG
  console.log("Main = ", materials.Main_Color);
  const cymbalMat = new THREE.MeshStandardMaterial().copy(materials.Main_Color);
  cymbalMat.color = new THREE.Color().setHex(0x85671e);

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-112.108, 24.109, -1.255]}
          rotation={[-1.687, 0.154, 0.737]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle003_Metal_0.geometry}
            material={cymbalMat}
          />
        </group>
        <group
          position={[77.893, 36.511, 10.948]}
          rotation={[-1.952, -0.358, -1.077]}
          scale={87.19}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle005_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle005_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-27.378, -9.941, -3.455]}
          rotation={[-1.937, 0.026, 0.01]}
          scale={98.452}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Black_Glossy001_0.geometry}
            material={materials["Black_Glossy.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Black_Glossy_0.geometry}
            material={materials.Black_Glossy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Black_transp_0.geometry}
            material={materials.Black_transp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Main_Color_0.geometry}
            material={materials.Main_Color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Transparent_0.geometry}
            material={materials.Transparent}
          />
        </group>
        <group
          position={[-101.726, -61.722, -29.315]}
          rotation={[0, -1.429, 0]}
          scale={125.653}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[0, -83.05, 7.258]}
          rotation={[Math.PI, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Black_Glossy001_0.geometry}
            material={materials["Black_Glossy.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Black_Glossy_0.geometry}
            material={materials.Black_Glossy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Black_transp_0.geometry}
            material={materials.Black_transp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Main_Color_0.geometry}
            material={materials.Main_Color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[62.037, -32.961, -42.612]}
          rotation={[-1.613, 0, 0]}
          scale={[109.274, 109.274, 84.339]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Black_Glossy001_0.geometry}
            material={materials["Black_Glossy.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Black_Glossy_0.geometry}
            material={materials.Black_Glossy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Black_transp_0.geometry}
            material={materials.Black_transp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Main_Color_0.geometry}
            material={materials.Main_Color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Transparent_0.geometry}
            material={materials.Transparent}
          />
        </group>
        <group
          position={[-76.083, -52.026, -32.901]}
          rotation={[-1.604, 0, 0]}
          scale={[104.533, 104.533, 174.097]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_Black_Glossy001_0.geometry}
            material={materials["Black_Glossy.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_Black_Glossy_0.geometry}
            material={materials.Black_Glossy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_Black_transp_0.geometry}
            material={materials.Black_transp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_Main_Color_0.geometry}
            material={materials.Main_Color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_Transparent_0.geometry}
            material={materials.Transparent}
          />
        </group>
        <group
          position={[-60.156, -61.722, -12.486]}
          rotation={[0, 0.666, 0]}
          scale={125.653}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-70.312, -61.722, -58.142]}
          rotation={[3.116, 0.222, -Math.PI]}
          scale={125.653}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[59.141, -114.005, -59.478]}
          rotation={[-3.037, 1.201, -0.279]}
          scale={157.215}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[54.734, -114.005, -38.402]}
          rotation={[-3.081, -0.89, -0.134]}
          scale={157.215}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[62.037, -76.599, -40.998]}
          rotation={[-1.608, 0, 0]}
          scale={[1.73, 1.73, 23.286]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder022_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder022_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[75.19, -114.005, -45.124]}
          rotation={[-0.038, -0.156, 2.954]}
          scale={157.215}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder025_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder025_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[79.489, -113.622, 5.182]}
          rotation={[-Math.PI, 1.256, -0.082]}
          scale={178.92}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder030_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder030_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[92.412, -113.622, 17.213]}
          rotation={[0, -0.309, 3.06]}
          scale={178.92}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder031_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder031_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[75.532, -113.622, 22.39]}
          rotation={[Math.PI, -0.839, -0.082]}
          scale={178.92}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder034_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder034_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-119.991, -115.563, 20.37]}
          rotation={[-3.119, -1.211, 0.136]}
          scale={178.92}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder035_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder035_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-125.756, -115.563, -16.401]}
          rotation={[-3.129, 0.884, 0.106]}
          scale={178.92}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder036_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder036_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[-90.622, -115.563, -2.732]}
          rotation={[-0.008, 0.163, -3.025]}
          scale={178.92}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder037_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder037_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[117.878, 13.805, -17.857]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.695, 1.695, 0.793]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder038_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder038_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[127.106, -95.963, 2.408]}
          rotation={[0, -1.229, 2.865]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder039_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder039_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[95.62, -95.963, -20.245]}
          rotation={[-Math.PI, 0.182, -0.277]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder040_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder040_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[130.981, -95.963, -36.186]}
          rotation={[0, 0.865, 2.865]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder041_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder041_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[0.063, -100.584, -36.502]}
          rotation={[1.246, 0, -Math.PI / 2]}
          scale={[-2.914, -2.902, -2.069]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder049_Beige_0.geometry}
            material={materials.Beige}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder049_Black_0.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder049_Metal_0.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          position={[26.33, -8.105, -2.623]}
          rotation={[2.699, -1.028, 3.052]}
          scale={98.452}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder067_Black_Glossy001_0.geometry}
            material={materials["Black_Glossy.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder067_Black_Glossy_0.geometry}
            material={materials.Black_Glossy}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder067_Black_transp_0.geometry}
            material={materials.Black_transp}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder067_Main_Color_0.geometry}
            material={materials.Main_Color}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder067_Metal_0.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder067_Transparent_0.geometry}
            material={materials.Transparent}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_Metal_0.geometry}
          material={materials.Metal}
          position={[117.878, 9.15, -17.857]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={62.192}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle007_Metal_0.geometry}
          material={materials.Metal}
          position={[117.878, 8.454, -17.857]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={62.192}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_Metal_0.geometry}
          material={materials.Metal}
          position={[0.035, -130.241, -49.687]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[131.054, 131.054, 111.804]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_Metal_0.geometry}
          material={materials.Metal}
          position={[4.379, -129.504, -62.443]}
          rotation={[-1.885, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_Metal_0.geometry}
          material={materials.Metal}
          position={[117.92, -130.25, -34.965]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[131.054, 131.054, 111.804]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_Metal_0.geometry}
          material={materials.Metal}
          position={[122.264, -129.654, -47.721]}
          rotation={[-1.885, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_Metal_0.geometry}
          material={materials.Metal}
          position={[35.195, -32.968, -42.616]}
          rotation={[-1.608, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_Metal_0.geometry}
          material={materials.Metal}
          position={[18.712, -37.796, 34.401]}
          rotation={[Math.PI / 2, -0.39, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_Metal_0.geometry}
          material={materials.Metal}
          position={[0, -34.129, 12.352]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[4.846, 4.846, 1.548]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015__0.geometry}
          material={materials["Cylinder.015__0"]}
          position={[-4.221, 3.938, 12.984]}
          rotation={[0, Math.PI / 4, 1.055]}
          scale={1.103}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_Metal_0.geometry}
          material={materials.Metal}
          position={[-4.224, 3.142, 12.449]}
          rotation={[0, Math.PI / 4, 1.055]}
          scale={1.103}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_Metal_0.geometry}
          material={materials.Metal}
          position={[117.843, -120.313, -18.379]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.306, -0.306, -5.76]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_Metal_0.geometry}
          material={materials.Metal}
          position={[117.878, -9.171, -17.857]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.609, 2.609, 1.787]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_Metal_0.geometry}
          material={materials.Metal}
          position={[-4.602, -2.032, 14.892]}
          rotation={[0, Math.PI / 4, 1.055]}
          scale={1.209}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020_Metal_0.geometry}
          material={materials.Metal}
          position={[-4.224, 3.142, 12.449]}
          rotation={[0, Math.PI / 4, 1.055]}
          scale={1.103}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_Metal_0.geometry}
          material={materials.Metal}
          position={[-4.221, 3.938, 12.984]}
          rotation={[0, Math.PI / 4, 1.055]}
          scale={1.103}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023_Metal_0.geometry}
          material={materials.Metal}
          position={[63.028, -77.415, -47.755]}
          rotation={[-Math.PI / 2, 0, 1.41]}
          scale={1.03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_Metal_0.geometry}
          material={materials.Metal}
          position={[76.674, 39.013, 9.17]}
          rotation={[-1.944, -0.385, 0.541]}
          scale={131.588}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder028_Metal_0.geometry}
          material={materials.Metal}
          position={[-4.224, 3.142, 12.449]}
          rotation={[0, Math.PI / 4, 1.055]}
          scale={1.103}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder029_Metal_0.geometry}
          material={materials.Metal}
          position={[82.258, 21.833, 14.099]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.584, -1.584, -8.184]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033_Metal_0.geometry}
          material={materials.Metal}
          position={[-112.025, -43.912, -0.184]}
          rotation={[-Math.PI / 2, 0, -1.968]}
          scale={[-1.584, -1.584, -8.184]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder042_Metal_0.geometry}
          material={materials.Metal}
          position={[7.998, -130.409, -31.428]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.642, -0.642, -8.364]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder043_Metal_0.geometry}
          material={materials.Metal}
          position={[-54.473, -92.281, 23.896]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={1.337}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder044_Metal_0.geometry}
          material={materials.Metal}
          position={[7.998, -114.868, -31.999]}
          rotation={[0, 1.571, 0]}
          scale={[-1.807, -1.829, -1.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder045_Metal_0.geometry}
          material={materials.Metal}
          position={[0.063, -114.868, -31.999]}
          rotation={[0, 1.571, 0]}
          scale={[-2.429, -2.458, -1.345]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder046_Metal_0.geometry}
          material={materials.Metal}
          position={[-7.968, -130.409, -31.428]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.642, -0.642, -8.364]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder047_Metal_0.geometry}
          material={materials.Metal}
          position={[-8.026, -114.868, -31.999]}
          rotation={[0, 1.571, 0]}
          scale={[-1.807, -1.829, -1.001]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder048_Metal_0.geometry}
          material={materials.Metal}
          position={[0.086, -112.678, -31.868]}
          rotation={[-1.91, 0, 0]}
          scale={[-0.496, -0.503, -5.603]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050__0.geometry}
          material={materials["Cylinder.015__0"]}
          position={[0.102, -120.875, -31.428]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.292, -0.292, -3.161]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder051_Metal_0.geometry}
          material={materials.Metal}
          position={[125.016, -131.748, -16.706]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.952, -0.952, -12.412]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder052_Metal_0.geometry}
          material={materials.Metal}
          position={[117.763, -107.837, -17.548]}
          rotation={[-Math.PI / 2, -0.016, 0]}
          scale={[4.825, 9.148, 3.325]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder053_Metal_0.geometry}
          material={materials.Metal}
          position={[117.948, -103.991, -17.839]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={[-2.393, -2.422, -1.453]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder054_Metal_0.geometry}
          material={materials.Metal}
          position={[110.785, -131.748, -16.706]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-0.952, -0.952, -12.412]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder055_Metal_0.geometry}
          material={materials.Metal}
          position={[125.229, -130.827, -20.919]}
          rotation={[Math.PI, -0.143, 0]}
          scale={[-0.442, -0.442, -14.763]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder056_Metal_0.geometry}
          material={materials.Metal}
          position={[7.562, -130.685, -34.992]}
          rotation={[Math.PI, -0.143, 0]}
          scale={[-0.442, -0.442, -14.763]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder057__0.geometry}
          material={materials["Cylinder.015__0"]}
          position={[-4.432, -0.834, 15.047]}
          rotation={[-3.126, -1.487, -2.085]}
          scale={1.209}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder058_Metal_0.geometry}
          material={materials.Metal}
          position={[-112.241, 12.652, -0.624]}
          rotation={[-1.567, 0.038, -1.587]}
          scale={131.588}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder059_Metal_0.geometry}
          material={materials.Metal}
          position={[117.894, 36.894, -17.96]}
          rotation={[-1.326, 0.15, -3.119]}
          scale={1.36}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder063_Black_0.geometry}
          material={materials.Black}
          position={[-54.473, -92.281, 24.098]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={1.337}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder064_Black_0.geometry}
          material={materials.Black}
          position={[-54.473, -92.281, 23.896]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={1.337}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder065_Metal_0.geometry}
          material={materials.Metal}
          position={[-59.907, -108.16, 39.286]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={1.38}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder066_Metal_0.geometry}
          material={materials.Metal}
          position={[-54.473, -92.281, 23.896]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={1.337}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder068_Black_0.geometry}
          material={materials.Black}
          position={[66.852, -123.467, 42.594]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={103.224}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder069_Metal_0.geometry}
          material={materials.Metal}
          position={[59.823, -108.174, 39.286]}
          rotation={[Math.PI / 2, -1.437, -Math.PI]}
          scale={1.38}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001__0.geometry}
          material={materials["Cylinder.015__0"]}
          position={[1.875, -131.508, -21.258]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[172.965, 111.222, 172.965]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/drumKit2.glb");
